# Generated by Django 4.1.7 on 2023-03-28 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatsapp', '0002_remove_message_author_contact_chat_message_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.ManyToManyField(related_name='set_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
